[package]
name = "rs_cudnn"
version = "0.1.0"
authors = ["Jason Cardinal <jason.cardinal@candeocreative.com>"]

link = "cudnn"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"